### ISSUE TITLE
Gregtech's Alloy Blast Furnace can't be parallelized despite JEI tooltip

### ISSUE THREAD

**Issue by Inevitabilis** [AllTheMods/ATM-9#1338]
For whatever reason the Alloy Blast Furnace multiblock can't be parallelized with parallel control hatches, even though JEI states it can be. 
The multiblock view in JEI shows that no block within ABF multiblock can be replaced with parallel control hatches either
![image](https://github.com/AllTheMods/ATM-9/assets/70079177/2961e26a-121a-4efe-84cf-5b0dd9044eb0)

**Comment by Mrminesheeps** [comment]
![image](https://github.com/AllTheMods/ATM-9/assets/15947037/e5c1d5bc-459c-4a51-9889-054d24115c41)
Seems the text was fixed. It may have been unintentionally listed.

**Comment by DeadlySoren** [comment]
Yeah, it still shows up in the listed uses for the parallel control hatch and I'm pretty sure I saw it in the scrolling list of blocks in the multiblock info screen for the ABS (though I can't be 100% sure because of how stupidly that screen is displayed)
Definitely sucks that this doesn't work as it would speed up late game GregTech by a lot
